title: WANG, Zheng's Homepage
page-top-title: Exploring AI & Building the Future
top-section-bg-text: WANG, Zheng
home-subtitle: WANG, Zheng&ensp;|&ensp;王 铮
copyright-text: '&copy; WANG, Zheng 2023-2026. All Rights Reserved.'
